### PR TITLE
Handle several config files through patterns

### PR DESCRIPTION
**Pull request by santigimeno**
- With this change, several config files defined in the configFile option with
  patterns are executed serially. If any of the tests fails, the task fails.
- For example you can use: configFile: 'test/**/testacular.conf.js'

### CODE REVIEW

**Comment by geddski** [comment]
Thanks @santigimeno, I'll take a look. Are they many benefits to this approach over just having multiple configs in the Gruntfile?

**Comment by santigimeno** [comment]
Hi,

For me, it made sense as I had many testacular.conf.js files and didn't want to create new targets for every one of them

BR

**Comment by geddski** [comment]
@santigimeno thank you again for contributing. I understand not wanting to create multiple targets each with duplicate config. I tackled this problem with a slightly different approach than what you've submitted, that I hope will keep gruntacular simple and yet still work for your use case.

I just pushed `0.2.0` that has support for sharing configuration settings between targets via `options`:

``` js
    testacular: {
      options: {
        configFile: 'testacular.conf.js',
        browsers: ['Chrome']
      },
      continuous: {
        singleRun: true
      },
      dev: {
        reporters: 'dots'
      }
    }
```

So in this example the `continuous` and `dev` targets will both use the common `configFile` and `runnerPort` settings as specified in the `options`. But the `continuous` target will override the browser setting to use PhantomJS, and also run as a singleRun. The `dev` target will simply change the reporter to dots.

So for your use case where you have many testacular.conf files, you could do something like this:

``` js
    testacular: {
      //common settings
      options: {
        basePath: '../',
        reporters: 'dots',
        browsers: ['Chrome', 'Firefox', 'Safari']
      },
      one: { configFile: 'testacular-one.conf.js' },
      two: { configFile: 'testacular-two.conf.js' },
      three: { configFile: 'testacular-three.conf.js' },
      four: { configFile: 'testacular-four.conf.js' }
    }
```

Another option testacular gives you is to [import directives from other files](https://github.com/vojtajina/testacular/wiki/Configuration-File-Overview).

Does that help? If that's still too much hassle, you could always [generate these targets programmatically](http://gruntjs.com/getting-started#project-and-task-configuration).

This should get you most of the way there. The only thing it doesn't address is running the targets serially, but testacular is so fast that shouldn't be a deal-breaker. I do want to see something like `grunt.registerSerialTask` though for this kind of thing in the future, I submitted the issue [parallel execution of multitask items](https://github.com/gruntjs/grunt/issues/527) to Grunt a few months ago and it's been added to the list of potential 0.5 features. Until then I don't want to add that complexity to this plugin, but I hope these `0.2.0` changes help. Thanks again!

**Comment by santigimeno** [comment]
@geddesign Thanks for your thorough response!. I'll try check all the information you provided and see how it works for me. Probably the first option you propose works for me.

BR

**Pull request closed without merging**
